SELECT COUNTRY.Continent, 
    IF( AVG(CITY.POPULATION) IS NULL, 0, FLOOR(AVG(CITY.POPULATION)))
FROM COUNTRY
INNER JOIN CITY
ON CITY.CountryCode = COUNTRY.Code
GROUP BY COUNTRY.Continent
-- ORDER BY COUNTRY.Continent;

-- SELECT DISTINCT(COUNTRY.CONTINENT)
-- FROM COUNTRY