SELECT HACKERS.HACKER_ID, NAME, SUM(FINAL_SCORE) AS TOTAL_SCORE
FROM (
    SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE) AS FINAL_SCORE
    FROM SUBMISSIONS
    GROUP BY HACKER_ID, CHALLENGE_ID
) MAX_SCORE_TABLE
JOIN HACKERS ON HACKERS.HACKER_ID = MAX_SCORE_TABLE.HACKER_ID
GROUP BY HACKERS.HACKER_ID, NAME
HAVING TOTAL_SCORE > 0
ORDER BY TOTAL_SCORE DESC, HACKERS.HACKER_ID;