/*
Enter your query here.
*/
SELECT HACKERS.HACKER_ID, HACKERS.NAME
FROM HACKERS
JOIN
(
    SELECT SUBMISSIONS.HACKER_ID, COUNT(DISTINCT SUBMISSIONS.CHALLENGE_ID) AS FREQUENCY
    FROM SUBMISSIONS
    JOIN CHALLENGES ON CHALLENGES.CHALLENGE_ID = SUBMISSIONS.CHALLENGE_ID
    JOIN DIFFICULTY ON CHALLENGES.DIFFICULTY_LEVEL = DIFFICULTY.DIFFICULTY_LEVEL
    WHERE SUBMISSIONS.SCORE = DIFFICULTY.SCORE
    GROUP BY SUBMISSIONS.HACKER_ID
    HAVING FREQUENCY > 1
)FREQ_TABLE ON FREQ_TABLE.HACKER_ID =  HACKERS.HACKER_ID
ORDER BY FREQUENCY DESC, HACKERS.HACKER_ID;


-- SELECT SUBMISSIONS.HACKER_ID, COUNT(DISTINCT SUBMISSIONS.CHALLENGE_ID) AS FREQUENCY
-- FROM SUBMISSIONS
-- JOIN CHALLENGES ON CHALLENGES.HACKER_ID = SUBMISSIONS.HACKER_ID
-- JOIN DIFFICULTY ON CHALLENGES.DIFFICULTY_LEVEL = DIFFICULTY.DIFFICULTY_LEVEL
-- GROUP BY SUBMISSIONS.HACKER_ID