/*
Enter your query here.
*/
SET @I = -1;
SELECT MIN(S) AS NEW_S, MIN(E) AS NEW_E
FROM (
    SELECT 
        IF(START_DATE NOT IN (SELECT END_DATE FROM PROJECTS), 
            @I := @I + 1, @I) AS ROWNUMBER,
        IF(START_DATE NOT IN (SELECT END_DATE FROM PROJECTS), 
            START_DATE, NULL) AS S,
        IF(END_DATE NOT IN (SELECT START_DATE FROM PROJECTS), 
            END_DATE, NULL) AS E
    FROM PROJECTS
    ORDER BY START_DATE, END_DATE
) PROJECTS_NEW
GROUP BY ROWNUMBER
ORDER BY DATEDIFF(MIN(E), MIN(S)) ASC;