SELECT COMPANY.COMPANY_CODE, FOUNDER, LM_COUNT, SM_COUNT, M_COUNT, E_COUNT
FROM COMPANY 
INNER JOIN 
(
    SELECT COMPANY_CODE, COUNT(DISTINCT LEAD_MANAGER_CODE) AS LM_COUNT
    FROM LEAD_MANAGER
    GROUP BY COMPANY_CODE
) LM_TABLE ON COMPANY.COMPANY_CODE = LM_TABLE.COMPANY_CODE
INNER JOIN 
(
    SELECT COMPANY_CODE, COUNT(DISTINCT SENIOR_MANAGER_CODE) AS SM_COUNT
    FROM SENIOR_MANAGER
    GROUP BY COMPANY_CODE
) SM_TABLE ON COMPANY.COMPANY_CODE = SM_TABLE.COMPANY_CODE
INNER JOIN 
(
    SELECT COMPANY_CODE, COUNT(DISTINCT MANAGER_CODE) AS M_COUNT
    FROM MANAGER
    GROUP BY COMPANY_CODE
)M_TABLE ON COMPANY.COMPANY_CODE = M_TABLE.COMPANY_CODE
INNER JOIN 
(
    SELECT COMPANY_CODE, COUNT(DISTINCT EMPLOYEE_CODE) AS E_COUNT
    FROM EMPLOYEE
    GROUP BY COMPANY_CODE
)E_TABLE ON COMPANY.COMPANY_CODE = E_TABLE.COMPANY_CODE
ORDER BY COMPANY.COMPANY_CODE;