/*
Enter your query here.
*/


SELECT CONCAT(NAME, '(', SUBSTRING(OCCUPATION, 1, 1), ')') AS FORMATTED_NAME
FROM OCCUPATIONS
ORDER BY FORMATTED_NAME;

SELECT CONCAT('There are a total of ', COUNT(*), ' ', LOWER(OCCUPATION), 's.') AS RESULT
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY RESULT;