/*
Enter your query here.
*/

SELECT IF(GRADES.GRADE < 8, NULL, STUDENTS.NAME), GRADES.GRADE, STUDENTS.MARKS
FROM STUDENTS
INNER JOIN GRADES
ON (GRADES.MIN_MARK <= STUDENTS.MARKS AND STUDENTS.MARKS <= GRADES.MAX_MARK)
ORDER BY GRADES.GRADE DESC, STUDENTS.NAME, STUDENTS.MARKS DESC;

-- HOW DOES JOIN WORK EXACTLY?
-- HOW DOES ROW NUMBER WORK ACC. TO PREDENCE I LEARNT ?